# A migration to add tables for Tag and Tagging. This file is automatically generated and added to your
# app if you run the tagging generator included with has_many_polymorphs.

# This migration moves from taggable, which is gone in rails 2.2, to has_many_polymorphs
class ChangeTagsToHasManyPolymorphs < ActiveRecord::Migration

  # I've commented out the bits from the generator that I don't need.
  def self.up
    # tags table - doesn't need to change much
    #create_table :tags do |t|
    #  t.column :name, :string, :null => false
    #end
    add_index :tags, :name, :unique => true
    
    # taggings table - some changes
    rename_table :posts_tags, :taggings
    rename_column :taggings, :post_id, :taggable_id # simply rename, should add :null => false ...
    add_column    :taggings, :id, :primary_key
    add_column    :taggings, :taggable_type, :string, { :default => "Post", :null => false }
    #create_table :taggings do |t|
    #  t.column :tag_id, :integer, :null => false
    #  t.column :taggable_id, :integer, :null => false
    #  t.column :taggable_type, :string, :null => false
    #  # t.column :position, :integer # Uncomment this if you need to use <tt>acts_as_list</tt>.
    #end
    add_index :taggings, [:tag_id, :taggable_id, :taggable_type], :unique => true    
  end

  def self.down
    remove_index :tags, :name
    remove_index :taggings, [:tag_id, :taggable_id, :taggable_type]
    rename_column :taggings, :taggable_id, :post_id
    remove_column :taggings, :taggable_type
    rename_table :taggings, :posts_tags
  end

end
